FC = ifort
LD = ifort

FFLAGS = -fpp -O3

SOURCES = solve_mod.f90 solver.f90 bndmat.f90 eqsil.f90 flux.f90 splnco.f90 intpol.f90

OBJECTS= $(SOURCES:.f90=.o)

.SUFFIXES: .f90 .o .mod 
%.o: %.f90
	$(FC) $(FFLAGS) -c $<

solver: $(OBJECTS)
	$(LD) -o solver $(OBJECTS) -ldislin

clean: 
	rm -f *.o solver *.mod